### ISSUE TITLE
Jobble logo does not load on main page

### ISSUE THREAD

**Issue by patrickmogan** [matthewmogan/Jobble#1]
Tested on Google Chrome 123.0.6312.124, likely problem with other browsers as well. Screenshot is attached
[
<img width="606" alt="Screenshot 2024-05-18 at 1 46 51 PM" src="https://github.com/matthewmogan/Jobble/assets/40368744/34210143-ba23-4fd9-a230-eb578c5986bd">
](url)

**Comment by patrickmogan** [comment]
@matthewmogan

**Comment by matthewmogan** [comment]
This should be resolved now - can you please try to replicate the issue?

**Comment by patrickmogan** [comment]
Thank you for fixing @matthewmogan!
